### ISSUE TITLE
Missing react native depenency

### ISSUE THREAD

**Issue by TAFE-tthom** [JfayTAFE/ROI-Staff-Directory#2]
https://github.com/JfayTAFE/ROI-Staff-Directory/blob/71fdfcbc4252c3f29dc8d70ed9809512cbee343f/StaffDirectory/package.json#L13-L14

Please include `"@react-navigation/native": "^6.1.17",` within your package.json file

**Comment by JfayTAFE** [comment]
Added "@react-navigation/native": "^6.1.17" to dependencies
